---
name: GetInEffects
version: 1.0.1
api: 1.12.0
author: TonyDroidd
main: TDroidd\GetInEffects\Main
description: Allows players to receive an effect when they join to server.
website: https://github.com/TonyDroidd/GetInEffects
permissions:
    gieffects.effect:
        default: op
        description: "Allow to receive the effect"
