# GetInEffects by TonyDroidd

#Effects ID's

#SPEED = 1
#SLOWNESS = 2
#HASTE = 3
# JoinEffect by TonyDroidd

#Effect ID's

#SPEED = 1
#SLOWNESS = 2
#HASTE = 3
#SWIFTNESS = 3
#FATIGUE = 4
#MINING_FATIGUE = 4
#STRENGTH = 5
#JUMP = 8
#NAUSEA = 9
#CONFUSION = 9
#REGENERATION = 10
#DAMAGE_RESISTANCE = 11
#FIRE_RESISTANCE = 12
#WATER_BREATHING = 13
#INVISIBILITY = 14
#WEAKNESS = 18
#POISON = 19
#WITHER = 20
#HEALTH_BOOST = 2

#Effect-ID: ID of the effect
#Duration in ticks: 1200 = 1 Minute | 20 = 1 second
#Amplifier = Power of the effect
#Particles: Show particles of the effect--> true / false

#Available Types: Tip, PupUp, Chat
Message-Type: "Tip"
#You can change it for another message (Leave in blank for disable)
Join-Effect-Message: "§aYou Get The §eSPEED §aEffect "

Effect-ID: "1"
Duration: "2400"
Amplifier: "0"
Particles: true
